---
# handlers file for haproxy
- name: Start and enabled haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
    enabled: true

- name: Start and enabled keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: restarted
    enabled: true