---
# handlers file for customer
- name: Start and enabled haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
    enabled: true

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes  

- name: Start and enabled nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true